ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Ms2ex.Repo, :manual)

Mimic.copy(Ms2ex.Storage)
Mimic.copy(Ms2ex.Context.Characters)
Mimic.copy(Ms2ex.Context.Wallets)
Mimic.copy(Ms2ex.Managers.Inventory)
Mimic.copy(Ms2ex.Managers.Quest)
Mimic.copy(Ms2ex.Managers.Achievement)
Mimic.copy(Ms2ex.Managers.Character)
Mimic.copy(Ms2ex.Managers.Field.Character)
Mimic.copy(Ms2ex.Net.SenderSession)
