services:
  postgres:
    image: postgres:16
    container_name: ms2ex-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: ms2ex-cache
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./priv/metadata.rdb:/data/dump.rdb

volumes:
  postgres:
