defmodule Ms2ex.Enums.GuildError do
  use Ms2ex.Enum, %{
    none: 0,
    s_guild_err_unknown: 1,
    s_guild_err_null_guild: 3,
    s_guild_err_already_exist: 4,
    s_guild_err_wait_inviting: 5,
    s_guild_err_blocked: 6,
    s_guild_err_has_guild: 7,
    s_guild_err_invalid_guild: 8,
    s_guild_err_null_user: 10,
    s_guild_err_name_exist: 11,
    s_guild_err_name_value: 12,
    s_guild_err_null_member: 13,
    s_guild_err_exist_member: 14,
    s_guild_err_full_member: 15,
    s_guild_err_not_join_member: 16,
    s_guild_err_cannot_leave_master: 17,
    s_guild_err_expel_target_master: 18,
    s_guild_err_not_enough_level: 19,
    s_guild_err_no_money: 20,
    s_guild_err_no_authority: 21,
    s_guild_err_no_master: 22,
    s_guild_err_invalid_grade_range: 23,
    s_guild_err_invalid_capacity_range: 24,
    s_guild_err_invalid_grade_data: 25,
    s_guild_err_invalid_grade_index: 26,
    s_guild_err_exist_empty_grade_index: 27,
    s_guild_err_set_grade_failed: 28,
    s_guild_err_fail_addmember: 30,
    s_guild_err_null_invite_member: 32,
    s_guild_err_cant_during_pvp: 33,
    s_guild_extend_capacity_err_cannot: 34,
    s_guild_extend_capacity_err_current: 35,
    s_guild_search_same_propensity: 36,
    s_guild_search_max_join_request: 37,
    s_guild_search_last_request: 38,
    s_guild_search_null_join_guild_request: 39,
    s_guild_err_fail_this_field: 41,
    s_guild_err_not_enough_guild_level: 42,
    s_guild_err_not_enough_guild_fund: 43,
    s_guild_err_cannot_use_skill: 44,
    s_guild_err_too_fast_to_search_by_name: 45,
    s_guild_pvp_already_pvp_field: 46
  }
end
