name: Generate and Deploy ExDocs

on:
  push:
    branches:
      - master
      - documentation

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Sets permissions for the GitHub token to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.x"
          otp-version: "27.x"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Generate Documentation
        run: mix docs

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./doc"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
